name: build Community Shaders and addons

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: build plugin and addons
    runs-on: windows-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
        - uses: actions/checkout@v3
          with:
            submodules: recursive

        - uses: ilammy/msvc-dev-cmd@v1.10.0

        - uses: lukka/run-vcpkg@v11.5
          with:
            vcpkgJsonGlob: vcpkg.json

        - name: Build using run-cmake with ALL preset
          uses: lukka/run-cmake@v10
          with:
            configurePreset: ALL
            buildPreset: ALL

        - name: extract version from CMake
          id: get_version
          run: |
            VERSION=$(grep 'CMAKE_PROJECT_VERSION:STATIC' build/ALL/CMakeCache.txt | cut -d= -f2)
            echo "version=$VERSION" >> $GITHUB_OUTPUT

  prerelease:
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: windows-latest
    steps:
      - name: upload prerelease
        uses: ncipollo/release-action@v1
        with:
          name: Community Shaders ${{ needs.build.outputs.version }} PR #${{ github.event.pull_request.number }}
          tag: v${{ needs.build.outputs.version }}-pr${{ github.event.pull_request.number }}
          prerelease: true
          artifacts: "${{ github.workspace }}/dist/CommunityShaders_AIO-*.7z"
          generateReleaseNotes: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: comment on PR
        if: success()
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ✅ A pre-release build is available for this PR:
            [Download](https://github.com/${{ github.repository }}/releases/tag/v${{ needs.build.outputs.version }}-pr${{ github.event.pull_request.number }})
          pr_number: ${{ github.event.pull_request.number }}

  release:
    needs: build
    if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    steps:
      - name: create tagged release
        uses: ncipollo/release-action@v1
        with:
          name: Community Shaders ${{ github.ref_name }}
          draft: true
          tag: ${{ github.ref_name }}
          artifacts: "${{ github.workspace }}/dist/*.7z"
          generateReleaseNotes: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}